package id.ac.ui.cs.advprog.papikos.chat.model;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;
import java.util.UUID;

class MessagesTest {
    private UserDummy sender;
    private static final UUID ROOM_ID = UUID.fromString("c12a3c98-b05f-4d67-a2cc-bc741577cf1a");
    private static final String CONTENT = "P, kamar tersedia?";

    @BeforeEach
    void setUp() {
        sender = new UserDummy();
        sender.setId(UUID.fromString("42abf604-4a75-4425-b98a-7fa6da52cc4b"));
        sender.setUsername("sender");
        sender.setRole(UserDummy.Role.USER);
    }

    @Test
    void testCreateMessageViaAllArgsConstructor() {
        LocalDateTime createdAt = LocalDateTime.now();
        LocalDateTime updatedAt = LocalDateTime.now();

        Message message = new Message(
                UUID.randomUUID(),
                ROOM_ID,
                sender.getId(),
                CONTENT,
                false,
                false,
                createdAt,
                updatedAt
        );

        assertNotNull(message.getMessageId());
        assertEquals(ROOM_ID, message.getRoomId());
        assertEquals(sender.getId(), message.getSenderUserId());
        assertEquals(CONTENT, message.getContent());
        assertFalse(message.isEdited());
        assertFalse(message.isDeleted());
        assertEquals(createdAt, message.getCreatedAt());
        assertEquals(updatedAt, message.getUpdatedAt());
    }

    @Test
    void testMessageContentCannotBeEmpty() {
        assertThrows(IllegalArgumentException.class, () -> {
            new Message(
                    ROOM_ID,
                    sender.getId(),
                    ""
            );
        });
    }

    @Test
    void testDefaultValuesViaCustomConstructor() {
        Message message = new Message(
                ROOM_ID,
                sender.getId(),
                CONTENT
        );

        assertNull(message.getMessageId());
        assertFalse(message.isEdited());
        assertFalse(message.isDeleted());
        assertNull(message.getCreatedAt());
    }

    @Test
    void testInvalidRoomId() {
        assertThrows(IllegalArgumentException.class, () -> {
            new Message(
                    null,
                    sender.getId(),
                    CONTENT
            );
        });
    }

    @Test
    void testNullContent() {
        assertThrows(IllegalArgumentException.class, () -> {
            new Message(
                    ROOM_ID,
                    sender.getId(),
                    null
            );
        });
    }

    @Test
    void testAutoGeneratedTimestamps() {
        Message message = new Message(
                ROOM_ID,
                sender.getId(),
                CONTENT
        );

        assertNull(message.getCreatedAt());
        assertNull(message.getUpdatedAt());
    }
}
